# Generated by Django 5.0.1 on 2024-02-12 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        #migrations.CreateModel(
        #    name='DoctorList',
        #    fields=[
        #        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('created_at', models.DateTimeField(auto_now_add=True)),
        #        ('first_name', models.CharField(max_length=50)),
        #        ('last_name', models.CharField(max_length=50)),
        #        ('Speciality', models.CharField(default='General', max_length=50)),
        #        ('phone', models.CharField(max_length=20)),
        #        ('facility_name', models.CharField(max_length=100)),
        #        ('city', models.CharField(max_length=50)),
        #        ('state', models.CharField(max_length=50)),
        #        ('email', models.CharField(max_length=100)),
        #    ],
        #),
        #migrations.CreateModel(
        #    name='Product',
        #    fields=[
        #        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('product_name', models.CharField(max_length=50)),
        #        ('product_description', models.TextField()),
        #        ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
        #        ('product_quantity', models.IntegerField()),
        #        ('product_category', models.CharField(max_length=50)),
        #    ],
        #),
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('assigned_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_region', to='website.salesrep')),
            ],
        ),
        migrations.CreateModel(
            name='MasterDoctorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('Hospital_name', models.CharField(max_length=100, verbose_name='Hospital Name')),
                ('location', models.CharField(max_length=100)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.salesrep')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('sales_reps_assigned', models.ManyToManyField(blank=True, related_name='supervisors_assigned', to='website.salesrep')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salesrep',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.supervisor'),
        ),
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateField()),
                ('visit_notes', models.TextField()),
                ('feedback', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdoctorlist')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.salesrep')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_notes', models.TextField()),
                ('feedback', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdoctorlist')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.salesrep')),
            ],
        ),
    ]
