# Generated by Django 5.0.1 on 2024-02-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlist',
            name='products_prescribing',
        ),
        migrations.RemoveField(
            model_name='doctorlist',
            name='user',
        ),
    ]
